import React from 'react';
import SplashScreen from './components/SplashScreen';
import type { Metadata } from 'next';
import { Open_Sans, Montserrat, Noto_Serif_Display } from 'next/font/google';
import './globals.css';

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin']
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin']
});

const notoSerifDisplay = Noto_Serif_Display({
  variable: '--font-noto-serif-display',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${openSans.variable} ${montserrat.variable} ${notoSerifDisplay.variable} antialiased`}>
        <SplashScreen>{children}</SplashScreen>
      </body>
    </html>
  );
}
